
package com.virtualpairprogrammers.employeemanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeManagementWebServiceImplementationService", targetNamespace = "http://employeemanagement.virtualpairprogrammers.com/", wsdlLocation = "http://localhost:8080/EmployeeManagement/EmployeeManagementWebService?wsdl")
public class EmployeeManagementWebServiceImplementationService
    extends Service
{

    private final static URL EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://employeemanagement.virtualpairprogrammers.com/", "EmployeeManagementWebServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EmployeeManagement/EmployeeManagementWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public EmployeeManagementWebServiceImplementationService() {
        super(__getWsdlLocation(), EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeManagementWebServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeManagementWebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeManagementWebServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeManagementWebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeManagementWebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeManagementWebService
     */
    @WebEndpoint(name = "EmployeeManagementWebServicePort")
    public EmployeeManagementWebService getEmployeeManagementWebServicePort() {
        return super.getPort(new QName("http://employeemanagement.virtualpairprogrammers.com/", "EmployeeManagementWebServicePort"), EmployeeManagementWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeManagementWebService
     */
    @WebEndpoint(name = "EmployeeManagementWebServicePort")
    public EmployeeManagementWebService getEmployeeManagementWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://employeemanagement.virtualpairprogrammers.com/", "EmployeeManagementWebServicePort"), EmployeeManagementWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return EMPLOYEEMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
