
package se.jpdc.soapmanagement;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HandSoapWeb", targetNamespace = "http://soapmanagement.jpdc.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HandSoapWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<se.jpdc.soapmanagement.HandSoap>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSoapsNyBrand", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.GetSoapsNyBrand")
    @ResponseWrapper(localName = "getSoapsNyBrandResponse", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.GetSoapsNyBrandResponse")
    public List<HandSoap> getSoapsNyBrand(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNewSoap", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.AddNewSoap")
    @ResponseWrapper(localName = "addNewSoapResponse", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.AddNewSoapResponse")
    public void addNewSoap(
        @WebParam(name = "arg0", targetNamespace = "")
        HandSoap arg0);

    /**
     * 
     * @return
     *     returns java.util.List<se.jpdc.soapmanagement.HandSoap>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSoaps", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.GetAllSoaps")
    @ResponseWrapper(localName = "getAllSoapsResponse", targetNamespace = "http://soapmanagement.jpdc.se/", className = "se.jpdc.soapmanagement.GetAllSoapsResponse")
    public List<HandSoap> getAllSoaps();

}
