
package se.jpdc.soapmanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPmanagementWebServiceImplementationService", targetNamespace = "http://soapmanagement.jpdc.se/", wsdlLocation = "http://localhost:8080/SoapManagement/HandSoapWeb?wsdl")
public class SOAPmanagementWebServiceImplementationService
    extends Service
{

    private final static URL SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://soapmanagement.jpdc.se/", "SOAPmanagementWebServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoapManagement/HandSoapWeb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public SOAPmanagementWebServiceImplementationService() {
        super(__getWsdlLocation(), SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public SOAPmanagementWebServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public SOAPmanagementWebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public SOAPmanagementWebServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public SOAPmanagementWebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPmanagementWebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HandSoapWeb
     */
    @WebEndpoint(name = "HandSoapWebPort")
    public HandSoapWeb getHandSoapWebPort() {
        return super.getPort(new QName("http://soapmanagement.jpdc.se/", "HandSoapWebPort"), HandSoapWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HandSoapWeb
     */
    @WebEndpoint(name = "HandSoapWebPort")
    public HandSoapWeb getHandSoapWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapmanagement.jpdc.se/", "HandSoapWebPort"), HandSoapWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return SOAPMANAGEMENTWEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
